version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "81:81"
      - "82:82" # Add this for serving the Laravel project
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
  php:
    container_name: container_php
    volumes:
      - ./app:/app
    build:
      context: .
      dockerfile: PHP.Dockerfile
  mysql:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: ${MARIADB_ALLOW_EMPTY_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: 'tutorial'
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: 'tutorial'
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysqldata: {}
